--CREATE TABLE DB1SMOKE.STG_AGE_RATINGS
--(
--AgeRatingId INT,
--AgeRatingName VARCHAR2(10),
--AgeRatingDescription VARCHAR2(100)
--);

--CREATE TABLE DB1SMOKE.STG_CONSOLES
--(
--ConsoleId INT,
--ConsoleName VARCHAR2(20)
--);

--CREATE TABLE DB1SMOKE.STG_GAME_CONSOLES
--(
--GameId INT,
--ConsoleId INT
--);

--CREATE TABLE DB1SMOKE.STG_GAMES
--(
--GameId INT,
--GameName VARCHAR2(100),
--GenreId INT,
--Price FLOAT,
--Rating FLOAT,
--AgeRating FLOAT
--);


--CREATE TABLE DB1SMOKE.STG_GENRE
--(
--GenreId INT,
--Genre VARCHAR2(20)
--);

--CREATE TABLE DB1SMOKE.STG_SUBSCRIPTION_TYPES
--(
--SubscriptionId INT,
--SubscriptionName VARCHAR2(10)
--);

--CREATE TABLE DB1SMOKE.STG_SUBSCRIPTIONS
--(
--UserId INT,
--GamerTag VARCHAR2(10),
--GameId INT,
--SubscriptionId INT
--);

--CREATE TABLE DB1SMOKE.STG_USERS
--(
--UserId INT,
--FirstName VARCHAR2(20),
--LastName VARCHAR2(20),
--GamerTag VARCHAR2(10),
--City VARCHAR2(20),
--Age INT,
--GamerScore INT,
--State VARCHAR2(30)
--);

---CREATE PROJECT TABLES --

--CREATE TABLE AGE_RATINGS AS
--SELECT * FROM STG_AGE_RATINGS

--CREATE TABLE CONSOLES AS
--SELECT * FROM STG_CONSOLES

--CREATE TABLE GAME_CONSOLES AS
--SELECT * FROM STG_GAME_CONSOLES

--CREATE TABLE GAMES AS
--SELECT * FROM STG_GAMES

--CREATE TABLE GENRE AS
--SELECT * FROM STG_GENRE

--CREATE TABLE SUBSCRIPTION_TYPES AS
--SELECT * FROM STG_SUBSCRIPTION_TYPES

--CREATE TABLE SUBSCRIPTIONS AS
--SELECT * FROM STG_SUBSCRIPTIONS

--CREATE TABLE USERS AS
--SELECT * FROM STG_USERS

-- TBD NON CLUSTERED INDEXS
--SELECT * FROM GAME_CONSOLES

--SELECT * FROM GAMES

-- ALTER TABLE AGE_RATINGS ADD CONSTRAINT PK_AGE_RATING_ID PRIMARY KEY (AGERATINGID);
--ALTER TABLE CONSOLES ADD CONSTRAINT PK_CONSOLE_ID PRIMARY KEY (CONSOLEID);

--ALTER TABLE GAMES ADD CONSTRAINT PK_GAME_ID PRIMARY KEY (GAMEID);
--ALTER TABLE GENRE ADD CONSTRAINT PK_GENRE_ID PRIMARY KEY (GENREID);
--ALTER TABLE SUBSCRIPTION_TYPES ADD CONSTRAINT PK_SUBSCRIPTION_ID PRIMARY KEY (SUBSCRIPTIONID);
--ALTER TABLE USERS ADD CONSTRAINT PK_USER_ID PRIMARY KEY (USERID);

-- Add foreign key constraints.
--ALTER TABLE GAMES 
--ADD CONSTRAINT FK_GENRE_ID
--FOREIGN KEY (GENREID) REFERENCES GENRE(GENREID);

--ALTER TABLE SUBSCRIPTIONS 
--ADD CONSTRAINT FK_SUBSCRIPTION_ID
--FOREIGN KEY (SUBSCRIPTIONID) REFERENCES SUBSCRIPTION_TYPES(SUBSCRIPTIONID);

--ALTER TABLE SUBSCRIPTIONS 
--ADD CONSTRAINT FK_GAME_ID
--FOREIGN KEY (GAMEID) REFERENCES GAMES(GAMEID);

--ALTER TABLE SUBSCRIPTIONS 
--ADD CONSTRAINT FK_USER_ID
--FOREIGN KEY (USERID) REFERENCES USERS(USERID);

--ALTER TABLE GAME_CONSOLES 
--ADD CONSTRAINT FK_CONSOLE_GAME_ID
--FOREIGN KEY (GAMEID) REFERENCES GAMES(GAMEID);

--ALTER TABLE GAME_CONSOLES 
--ADD CONSTRAINT FK_CONSOLE_ID
--FOREIGN KEY (CONSOLEID) REFERENCES CONSOLES(CONSOLEID);

--ALTER TABLE GAMES 
--ADD CONSTRAINT FK_AGE_RATING
--FOREIGN KEY (AGERATING) REFERENCES AGE_RATINGS(AGERATINGID);

--SELECT * FROM AGE_RATINGS
--FETCH NEXT 4 ROWS ONLY

-- Create Indexes--
--CREATE INDEX IDX_GAMECONSOLE_GAMEID
--ON GAME_CONSOLES(GAMEID);

--CREATE INDEX IDX_GAMECONSOLE_CONSOLEID
--ON GAME_CONSOLES(CONSOLEID);

--CREATE INDEX IDX_GAMES_GENREID
--ON GAMES(GENREID);

--CREATE INDEX IDX_GAMES_AGERATING
--ON GAMES(AGERATING);

--CREATE INDEX IDX_SUBSCRIPTIONS_USERID
--ON SUBSCRIPTIONS(USERID);

--CREATE INDEX IDX_SUBSCRIPTIONS_GAMEID
--ON SUBSCRIPTIONS(GAMEID);

--CREATE INDEX IDX_SUBSCRIPTIONS_SUBSID
--ON SUBSCRIPTIONS(SUBSCRIPTIONID);

--CREATE INDEX IDX_SUBSCRIPTIONS_GAMERTAG
--ON SUBSCRIPTIONS(GAMERTAG);

--CREATE INDEX IDX_USERS_GAMERTAG
--ON USERS(GAMERTAG);
